export const carData = [
  {
    "id":1,
    "brand": "SMART",
    "model": "ForFour",
    "generation": "2nd Gen ",
    "year": "2019",
    "mileage":"90,000 km",
    "doors": 4,
    "color": "Yellow with black roof",
    "body_style": "Hatchback",
    "fuel_type": "Petrol",
    "transmission": "Manual or Automatic",
    "Price":14000,
    "img":"1.png",
  },
  {
    "id":2,
    "brand": "FORD",
    "model": "Focus",
    "generation": "3rd Gen ",
    "year": "2015",
    "mileage":"30,000 km",
    "doors": 4,
    "color": "Dark Grey",
    "body_style": "Hatchback",
    "fuel_type": "Diesel",
    "transmission": "Automatic",
    "Price":9000,
    "img":"7.png",
    
  },
  {
    "id":3,
    "brand": "LEXUS",
    "model": "LS 460",
    "generation": "4th Gen (XF40)",
    "year": "2012",
    "mileage":"20,000 km",
    "doors": 4,
    "color": "Black",
    "body_style": "sedan",
    "fuel_type": "Petrol",
    "transmission": "Automatic",
    "Price":16820,
    "img":"5.png",
    
  },
  {
    "id":4,
    "brand": "MERCEDES-BENZ",
    "model": "A-Class",
    "generation": "Recent generation",
    "year": "2018",
    "mileage": "70,000 km",
    "doors": 4,
    "color": "Blue",
    "body_style": "Hatchback",
    "fuel_type": "Gasoline or Diesel",
    "transmission": "Automatic",
    "Price": 33650,
    "img":"4.png"
},
{
    "id": 5,
    "brand": "NISSAN",
    "model": "Pathfinder",
    "generation": "Recent generation",
    "year": " 2023",
    "mileage": "50,000 km",
    "doors": 4,
    "color": "Blue",
    "body_style": "SUV",
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "Price": 45050,
    "img": "2.png"
},
{
    "id": 6,
    "brand": "FORD",
    "model": "Mustang",
    "generation": "Recent generation",
    "year": "2019",
    "mileage": "50,000 km",
    "doors": 4,
    "color": "olive Green",
    "body_style": "Convertible",
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "Price": 21100,
    "img": "3.png",
},
{
    "id": 7,
    "brand": "FORD",
    "model": "F-150",
    "generation": "14th Gen (P702)",
    "year": "2021",
    "mileage": "None",
    "doors": 4,
    "color": "White",
    "body_style": "Pickup truck",
    "fuel_type": "Gasoline",
    "transmission": "Automatic",
    "Price": 36900,
    "img": "6.png",
},
{
     "id":8,
    "brand": "RENAULT",
    "model": "Kwid Outsider",
    "generation": "1st",
    "year": "2019 ",
    "mileage": "20,000 km",
    "doors": 4,
    "color": "Blue",
    "body_style": "SUV",
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "Price": 12700,
    "img":"8.png",
},
{
    "id":9,
    "brand": "RENAULT",
    "model": "Captur",
    "generation": "2nd Generation",
    "year": "2020 ",
    "mileage": "40,000 km",
    "doors": 4,
    "color": "Blue and white",
    "body_style": "SUV",
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "Price": 22600,
    "img":"9.png",
},
{
    "id":10,
    "brand": "RENAULT",
    "model": "Arkana",
    "generation": "1st Generation",
    "year": "2021",
    "mileage": "Varies",
    "doors": 4,
    "color": "Black",
    "body_style": "SUV",
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "Price": 36200,
    "img":"10.png",
},
{
    "id":11,
    "brand": "FORD",
    "model": "Maverick",
    "generation": "2025",
    "year": "2025",
    "mileage": "30,000 km",
    "doors": 4,
    "color": "Blue",
    "body_style": "Pickup Truck",
    "fuel_type": "Hybrid or Gasoline",
    "transmission": "Hybrid",
    "Price": 28690,
    "img":"11.png",

},
{
    "id":12,
    "brand": "TOYOTA",
    "model": "Venza",
    "generation": "3rd",
    "year": "2021",
    "mileage": "None",
    "doors": 4,
    "color": "Gray",
    "body_style": "SUV",
    "fuel_type": "Hybrid ",
    "transmission": "Automatic",
    "Price": 25000,
    "img":"12-copie1.png",
},
{
    "id":13,
    "brand": "TOYOTA",
    "model": "Venza",
    "generation": "3rd",
    "year": "2021",
    "mileage": "None",
    "doors": 4,
    "color": "Gray",
    "body_style": "SUV",
    "fuel_type": "Hybrid ",
    "transmission": "Automatic",
    "Price": 17000,
    "img":"13-copie1.png",
},
{
    "id":14,
    "brand": "TOYOTA",
    "model": "Venza",
    "generation": "3rd",
    "year": "2021",
    "mileage": "None",
    "doors": 4,
    "color": "Gray",
    "body_style": "SUV",
    "fuel_type": "Hybrid ",
    "transmission": "Automatic",
    "Price": 40000,
    "img":"14-copie1.png",
},
{
    "id":15,
    "brand": "TOYOTA",
    "model": "Venza",
    "generation": "3rd",
    "year": "2021",
    "mileage": "None",
    "doors": 4,
    "color": "Gray",
    "body_style": "SUV",
    "fuel_type": "Hybrid ",
    "transmission": "Automatic",
    "Price": 17000,
    "img":"15-copie1.png",
},
{
    "id":16,
    "brand": "MERCEDES-BENZ",
    "model": "Venza",
    "generation": "3rd",
    "year": "2021",
    "mileage": "None",
    "doors": 4,
    "color": "Gray",
    "body_style": "SUV",
    "fuel_type": "Hybrid ",
    "transmission": "Automatic",
    "Price": 28000,
    "img":"16-copie1.png",
},
{
    "id":17,
    "brand": "AUDI",
    "model": "Venza",
    "generation": "3rd",
    "year": "2021",
    "mileage": "None",
    "doors": 4,
    "color": "Gray",
    "body_style": "SUV",
    "fuel_type": "Hybrid ",
    "transmission": "Automatic",
    "Price": 50000,
    "img":"17-copie1.png",
},
{
    "id":18,
    "brand": "BMW",
    "model": "Venza",
    "generation": "3rd",
    "year": "2021",
    "mileage": "NONE",
    "doors": 4,
    "color": "Gray",
    "body_style": "SUV",
    "fuel_type": "Hybrid ",
    "transmission": "Automatic",
    "Price": 30000,
    "img":"18-copie5.png",
},
{
    "id":19,
    "brand": "AUDI",
    "model": "Venza",
    "generation": "3rd",
    "year": "2021",
    "mileage": "NONE",
    "doors": 4,
    "color": "Gray",
    "body_style": "SUV",
    "fuel_type": "Hybrid ",
    "transmission": "Automatic",
    "Price": 40000,
    "img":"19.png",
},{
    "id":20,
    "brand": "TOYOTA",
    "model": "Venza",
    "generation": "3rd",
    "year": "2021",
    "mileage": "NONE",
    "doors": 4,
    "color": "Gray",
    "body_style": "SUV",
    "fuel_type": "Hybrid ",
    "transmission": "Automatic",
    "Price":37329,
    "img":"20-copie1.png",
},
]
